# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82e89de9c1fc3e6f23b85ba1e93488b4cafac27fa4301f93aeffba91e523b092fd4b46ecb040f885fb0af07087e6ee5785ff96a26fbe7c021b6dc715dae2bdef

test:
  secret_key_base: 49083b4e6f89b75b6bc17b9c08da22019b06a6415cc021dcff7812ba25e4402bed4f13443b1f4410056be086a76b61e5c328d0660f65b7d71b4914a58bf33078

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
